-- inserts for test data
-- ARTISTS
insert into Artist (Name) values ('Harber-Kassulke');
insert into Artist (Name) values ( 'O''Connell and Sons');
insert into Artist (Name) values ( 'Hoeger-Senger');
insert into Artist (Name) values ( 'Glover, Fahey and Bailey');
insert into Artist (Name) values ( 'Christiansen-Satterfield');
insert into Artist (Name) values ( 'Stiedemann LLC');
insert into Artist (Name) values ( 'Casper, Grady and Koelpin');
insert into Artist (Name) values ( 'Moen Group');
insert into Artist (Name) values ( 'Boyer-Quigley');
insert into Artist (Name) values ( 'Oberbrunner, Batz and Kessler');

-- ALBUMS
insert into Album (Title, ArtistId) values ('Ventosanzap', 1);
insert into Album (Title, ArtistId) values ('Asoka', 2);
insert into Album (Title, ArtistId) values ('Zoolab', 3);
insert into Album (Title, ArtistId) values ('Zamit', 4);
insert into Album (Title, ArtistId) values ( 'Konklux', 5);
insert into Album (Title, ArtistId) values ( 'Prodder', 6);
insert into Album (Title, ArtistId) values ( 'Rank', 7);
insert into Album (Title, ArtistId) values ( 'Voltsillam', 8);
insert into Album (Title, ArtistId) values ( 'Fintone', 9);
insert into Album (Title, ArtistId) values ( 'Redhold', 10);

insert into Album (Title, ArtistId) values ( 'Viva', 1);
insert into Album (Title, ArtistId) values ( 'Solarbreeze', 2);
insert into Album (Title, ArtistId) values ( 'Regrant', 3);
insert into Album (Title, ArtistId) values ( 'Gembucket', 4);
insert into Album (Title, ArtistId) values ( 'Zoolab', 5);
insert into Album (Title, ArtistId) values ( 'Cookley', 6);
insert into Album (Title, ArtistId) values ( 'Treeflex', 7);
insert into Album (Title, ArtistId) values ( 'Bitchip', 8);
insert into Album (Title, ArtistId) values ( 'Asoka', 9);
insert into Album (Title, ArtistId) values ( 'Sonsing', 10);

--TRACKS
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Anthropoides paradisea', 5, 2, 4, 'Faulkner Spire', 9172, 518, 12.32);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Colobus guerza', 5, 1, 1, 'Shermy Littlefield', 3579, 542, 57.23);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Picoides pubescens', 11, 2, 3, 'Caresa Mullin', 3821, 674, 37.54);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Delphinus delphis', 18, 5, 3, 'Delia MacIntyre', 6206, 351, 36.99);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Macropus rufogriseus', 5, 3, 19, 'Rhetta Ecclestone', 9656, 991, 56.56);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Dasyurus viverrinus', 15, 5, 11, 'Ford Baxandall', 3463, 707, 53.91);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Ateles paniscus', 17, 4, 17, 'Mariele Wheildon', 1614, 114, 65.63);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('unavailable', 3, 2, 7, 'Opalina Heister', 6092, 308, 8.21);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Antechinus flavipes', 13, 3, 25, 'Tildi Blackledge', 6809, 793, 4.33);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Connochaetus taurinus', 3, 4, 6, 'Horace Keasey', 5998, 860, 60.43);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Alectura lathami', 1, 1, 13, 'Tabor Kornas', 1441, 449, 88.34);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Sarkidornis melanotos', 2, 2, 2, 'Eugenie Willows', 5716, 375, 81.58);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Bison bison', 3, 4, 25, 'Darren Heathfield', 4995, 555, 18.82);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Pycnonotus barbatus', 7, 4, 10, 'Ajay Loidl', 8443, 567, 18.51);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Macropus robustus', 14, 4, 6, 'Mariam Siggery', 8368, 223, 36.92);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Morelia spilotes variegata', 11, 2, 6, 'Bing Hinks', 6997, 908, 22.87);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Neotoma sp.', 19, 4, 20, 'Martica Tipper', 4285, 749, 81.42);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Streptopelia senegalensis', 7, 1, 7, 'Marilee Tootal', 3716, 610, 28.34);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Lybius torquatus', 8, 5, 12, 'Nydia Dioniso', 7152, 607, 6.57);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Tockus flavirostris', 8, 4, 3, 'Marcella Soreau', 5120, 153, 88.23);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Pycnonotus nigricans', 5, 2, 14, 'Rozelle Mulqueeny', 3729, 580, 61.23);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Varanus albigularis', 11, 1, 17, 'Elden Olle', 2457, 944, 36.1);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Crotaphytus collaris', 20, 3, 21, 'Dorene Saker', 4504, 477, 49.7);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Ratufa indica', 12, 4, 6, 'Napoleon Conochie', 8864, 416, 87.88);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Delphinus delphis', 5, 4, 4, 'Skelly Dinesen', 4145, 254, 73.65);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Globicephala melas', 10, 2, 10, 'Micki Stidson', 5896, 224, 74.32);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Dendrocitta vagabunda', 15, 2, 7, 'Rachael Shapera', 3073, 684, 20.23);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Snycerus caffer', 5, 3, 12, 'Vernor Furzey', 1017, 606, 77.38);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Nannopterum harrisi', 9, 2, 18, 'Vittorio Kitchingham', 5428, 701, 29.08);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Ovis ammon', 10, 3, 11, 'Rex Gloucester', 9349, 982, 79.76);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Gymnorhina tibicen', 14, 4, 17, 'Thatch Scimone', 6839, 390, 11.59);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Varanus komodensis', 17, 4, 14, 'Ibrahim Kesper', 5424, 797, 20.7);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Colobus guerza', 1, 5, 19, 'Ruthann Paddeley', 7779, 834, 89.22);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Tauraco porphyrelophus', 19, 2, 9, 'Tobie Deeney', 7619, 161, 97.73);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Cervus canadensis', 1, 3, 25, 'Sholom Ulrik', 4902, 452, 40.41);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Gopherus agassizii', 3, 2, 22, 'Kurt Genike', 5139, 110, 39.55);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Gyps bengalensis', 13, 3, 22, 'Stephine Tsarovic', 7292, 489, 39.68);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Dasypus novemcinctus', 9, 4, 19, 'Geordie Luparto', 9056, 624, 20.28);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Cervus elaphus', 4, 2, 4, 'Bev Glitherow', 8872, 230, 10.51);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Nucifraga columbiana', 11, 1, 12, 'Yancey Tuxill', 8613, 745, 16.9);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Passer domesticus', 4, 5, 16, 'Ambrosio Stollenwerck', 8819, 535, 5.34);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Himantopus himantopus', 12, 3, 24, 'Nate Iddiens', 5041, 970, 6.99);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Fulica cristata', 4, 1, 6, 'Alberta Fosten', 1512, 514, 18.39);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Sitta canadensis', 2, 2, 10, 'Daron Cotta', 6652, 244, 66.75);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Vombatus ursinus', 7, 5, 21, 'Jeri Lesurf', 4073, 221, 61.52);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Boselaphus tragocamelus', 2, 1, 21, 'Ned Chin', 6962, 905, 14.78);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Semnopithecus entellus', 1, 2, 5, 'Vidovik Riquet', 1831, 834, 96.53);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Bison bison', 1, 5, 4, 'Roxanne Joseff', 4730, 513, 61.8);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Ephippiorhynchus mycteria', 15, 3, 2, 'Bernelle Fullom', 4742, 766, 92.31);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Sarcorhamphus papa', 2, 2, 15, 'Debi Garvey', 8245, 963, 69.35);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Dusicyon thous', 14, 3, 13, 'Dulcinea Garwell', 6829, 719, 3.15);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Phalaropus lobatus', 19, 2, 23, 'Lothaire Tomkiss', 3313, 802, 91.86);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Ctenophorus ornatus', 12, 3, 19, 'Barn Blaycock', 8382, 190, 75.77);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Melanerpes erythrocephalus', 5, 1, 5, 'Cam Cantera', 4729, 169, 26.93);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Gazella granti', 5, 5, 3, 'Jareb Pattinson', 2623, 851, 44.28);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Antilope cervicapra', 1, 3, 22, 'Steffen Toffolo', 1505, 520, 88.0);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Pycnonotus barbatus', 12, 2, 23, 'Kim Rablen', 8002, 406, 11.33);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Cervus canadensis', 8, 3, 8, 'Cordie Avent', 7720, 246, 50.35);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Nesomimus trifasciatus', 13, 5, 23, 'Lena Brisley', 5651, 250, 21.51);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Dasyurus maculatus', 14, 4, 24, 'Jasmin Kid', 7164, 404, 2.17);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Junonia genoveua', 11, 4, 16, 'Dewitt Pracy', 9663, 904, 92.14);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Loris tardigratus', 15, 2, 15, 'Eleen Janson', 9899, 978, 40.64);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('unavailable', 17, 1, 11, 'Clemmy Murrill', 5145, 381, 33.83);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Branta canadensis', 5, 2, 9, 'Frederic Royall', 4329, 832, 72.53);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Seiurus aurocapillus', 6, 2, 23, 'Thomasina Irlam', 9241, 283, 23.51);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Pandon haliaetus', 16, 2, 9, 'Benoite Cordell', 2302, 153, 2.17);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Ara ararauna', 13, 4, 23, 'Courtney Legge', 5083, 489, 31.08);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Buteo regalis', 12, 4, 21, 'Elly Durrell', 3557, 978, 46.69);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Canis aureus', 1, 2, 7, 'Wendeline Triggle', 7279, 683, 34.19);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Scolopax minor', 17, 1, 24, 'Calhoun Ainslie', 1215, 766, 9.56);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Ammospermophilus nelsoni', 19, 3, 2, 'Moshe Youthead', 4482, 738, 74.44);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Felis caracal', 6, 5, 22, 'Goldarina Benezet', 3742, 978, 50.68);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Phylurus milli', 8, 3, 6, 'Kellina Kuhnert', 2311, 669, 21.16);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Lutra canadensis', 6, 3, 1, 'Sheree Shardlow', 8548, 262, 90.05);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Antidorcas marsupialis', 6, 4, 18, 'Amata Camplen', 5404, 273, 23.87);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Anathana ellioti', 18, 3, 15, 'Gnni Fernyhough', 1442, 332, 5.38);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Globicephala melas', 6, 4, 23, 'Clarice Yakunchikov', 5896, 155, 32.93);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Cacatua galerita', 11, 1, 9, 'Nicola Landells', 6133, 756, 58.72);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Halcyon smyrnesis', 4, 5, 15, 'Ilario Upfold', 9781, 139, 12.92);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Xerus sp.', 16, 2, 4, 'Lory Kiehne', 5631, 329, 10.49);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Cygnus buccinator', 19, 2, 7, 'Gerick Dewer', 5456, 471, 13.7);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Grus rubicundus', 5, 2, 5, 'Atalanta Rubinfeld', 3484, 242, 29.02);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Heloderma horridum', 3, 1, 5, 'Eberto Theodore', 7183, 935, 66.24);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Erethizon dorsatum', 3, 2, 25, 'Tripp Piatkow', 6145, 509, 98.36);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('unavailable', 11, 4, 25, 'Tiffani Hairyes', 7564, 523, 77.47);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Zenaida galapagoensis', 4, 5, 24, 'Randi Filippone', 5780, 896, 38.46);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Paradoxurus hermaphroditus', 20, 1, 3, 'Rhona Petroulis', 4319, 508, 49.49);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Felis wiedi or Leopardus weidi', 1, 4, 5, 'Madelon Berget', 3378, 731, 33.44);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Corythornis cristata', 3, 3, 23, 'Sigismund Bryns', 5423, 729, 97.76);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Rhabdomys pumilio', 3, 5, 13, 'Maddi Veale', 4866, 622, 89.62);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Stenella coeruleoalba', 9, 4, 2, 'Sonnie Shurville', 3833, 901, 89.6);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Capreolus capreolus', 1, 1, 20, 'Micheil Priddey', 6651, 551, 38.52);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Meles meles', 12, 1, 24, 'Rochester Suddick', 5006, 641, 40.1);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Geochelone radiata', 7, 3, 15, 'Augustina Jacobsson', 5764, 480, 64.03);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Butorides striatus', 14, 4, 25, 'Harris Godart', 1055, 171, 43.23);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Axis axis', 8, 5, 20, 'Bibbie Bielfeldt', 2791, 232, 82.78);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Cyrtodactylus louisiadensis', 5, 3, 5, 'Elwin Ferrar', 6656, 327, 60.46);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Trichechus inunguis', 1, 5, 11, 'Sissie Corington', 3912, 745, 69.52);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Bos mutus', 4, 1, 23, 'Bendicty Matthias', 9260, 946, 37.38);
insert into Track (Name, AlbumId, MediaTypeId, GenreId, Composer, Milliseconds, Bytes, UnitPrice) values ('Butorides striatus', 5, 1, 21, 'Giovanni Barfitt', 8691, 756, 44.01);