#app settings
#jdbc.datasource.url=jdbc:mysql://localhost:3306/expensereimbursements
#jdbc.datasource.username=root
#jdbc.datasource.password=Newlife123

# default config
server:
  port: 8080

spring:  
  datasource:
    url: jdbc:mysql://localhost:3306/inventory
    username: root
    password: Newlife123
    
  jpa:
    # please use Pascal_Case so you don't need this:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: none